# Generated by Django 4.2.10 on 2024-02-26 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pulsewave.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Доска')),
                ('members', models.ManyToManyField(related_name='joined_boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Колонка')),
                ('index', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_board', to='workspaces.board')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Рабочее пространство')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('invited', models.ManyToManyField(related_name='invited_to_workspaces', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='joined_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('index', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('deadline', models.DateTimeField(null=True, verbose_name='Срок выполнения')),
                ('description', models.CharField(blank=True, max_length=2048, verbose_name='Описание')),
                ('file', models.FileField(null=True, upload_to='task_attach/')),
                ('priority', models.IntegerField(choices=[(0, 'Срочный'), (1, 'Высокий'), (2, 'Нормальный'), (3, 'Низкий')], null=True, verbose_name='Флаг приоритета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания задачи')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='workspaces.column')),
                ('responsible', models.ManyToManyField(related_name='responsible_for_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название стикера')),
                ('color', models.CharField(max_length=7, validators=[pulsewave.validators.validate_sticker_color], verbose_name='Цвет')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticker', to='workspaces.task')),
            ],
        ),
        migrations.CreateModel(
            name='InvitedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_invitations', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2048, verbose_name='Комментарий')),
                ('created_data', models.DateTimeField(auto_now_add=True, verbose_name='Время создания комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workspaces.task')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='workspaces.workspace'),
        ),
    ]
