# Generated by Django 4.2.5 on 2023-11-24 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Рабочее пространство')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('invited', models.ManyToManyField(related_name='workspace_invited', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='workspace_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Доска')),
                ('members', models.ManyToManyField(related_name='board_members', to=settings.AUTH_USER_MODEL)),
                ('work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='workspaces.workspace')),
            ],
        ),
    ]
