# Generated by Django 4.2.5 on 2023-12-05 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0002_alter_board_members_alter_board_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Колонка')),
                ('index', models.IntegerField(verbose_name='Порядковый номер')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_board', to='workspaces.board')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название задачи')),
                ('index', models.IntegerField(verbose_name='Порядковый номер')),
                ('deadline', models.DateField(null=True, verbose_name='Срок выполнения')),
                ('description', models.CharField(blank=True, max_length=2048, verbose_name='Описание')),
                ('file', models.FileField(null=True, upload_to='task_attach/')),
                ('priority', models.IntegerField(choices=[(0, 'Срочный'), (1, 'Высокий'), (2, 'Нормальный'), (3, 'Низкий')], null=True, verbose_name='Флаг приоритета')),
                ('color_mark', models.CharField(blank=True, max_length=16, verbose_name='Цветовая метка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания задачи')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='workspaces.column')),
                ('responsible', models.ManyToManyField(related_name='responsible_for_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
