# Generated by Django 4.2.8 on 2023-12-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_column_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name_mark',
            field=models.CharField(blank=True, max_length=16, verbose_name='Название метки'),
        ),
    ]
