# Generated by Django 4.2.8 on 2023-12-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_task_name_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='index',
            field=models.PositiveIntegerField(verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='task',
            name='index',
            field=models.PositiveIntegerField(verbose_name='Порядковый номер'),
        ),
    ]
