# Generated by Django 4.2.9 on 2024-01-07 16:34

from django.db import migrations, models
import pulsewave.validators


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_alter_sticker_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='color',
            field=models.CharField(max_length=7, validators=[pulsewave.validators.validate_sticker_color], verbose_name='Цвет'),
        ),
    ]
