# Generated by Django 4.2.10 on 2024-03-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название задачи'),
        ),
    ]
