# Generated by Django 4.2.11 on 2024-04-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_alter_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='work_space',
            new_name='workspace',
        ),
    ]
