stages:
  - build
#  - delivery

build:
  stage: build
  services:
    - docker:stable-dind
  before_script:
    - echo "$DOCKER_KEY" | docker login --username $DOCKER_USER --password-stdin
  script:
    - docker build --network host -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE


#delivery:
#  stage: delivery
#  before_script:
#    - echo "$DOCKER_KEY" | docker login --username $DOCKER_USER --password-stdin
#  script:
#    - set -e
#    - docker tag pulsewave-drf-api-django:latest $CI_REGISTRY_IMAGE
#    - docker push $CI_REGISTRY_IMAGE




