stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - echo "$DOCKER_KEY" | docker login --username $DOCKER_USER --password-stdin
  script:
    - docker build --network host -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master

deploy:
  stage: deploy
  image: docker:20.10-git
  dependencies:
    - build
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - echo "$DOCKER_KEY" | docker login --username $DOCKER_USER --password-stdin
  script:
    - docker compose --env-file $env pull
    - docker run --rm --env-file $env --network $NETWORK --entrypoint "./migrate.sh" $CI_REGISTRY_IMAGE migrate.sh
    - docker compose --env-file $env down --timeout=60
    - docker compose --env-file $env up --build --detach
    - docker system prune -a -f || true
  only:
    - master
