stages:
  - build
  - delivery
#  - deploy

build:
  stage: build
  script:
    - set -e
    - docker network ls
    - docker volume ls
    - docker-compose down || true
    - docker-compose build pw-django
    - docker-compose up


delivery:
  stage: delivery
  before_script:
    - echo "$DOCKER_KEY" | docker login --username $DOCKER_USER --password-stdin
  script:
    - set -e
    - docker tag pw-django:latest $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE




