stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - echo "$DOCKER_KEY" | docker login --username $DOCKER_USER --password-stdin
  script:
    - docker build --network host -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master
  tags:
    - back
#  when: manual

deploy:
  stage: deploy
  image: docker:20.10-git
#  needs: []
  dependencies:
    - build
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - echo "$DOCKER_KEY" | docker login --username $DOCKER_USER --password-stdin
    - chmod +x ./ci/db_dump.sh
  script:
    - docker compose pull
#    - ./ci/db_dump.sh
    - docker run --rm --env-file $env --network db-net --entrypoint "./ci/migrate.sh" $CI_REGISTRY_IMAGE
    - docker stack deploy -c docker-compose.yml back
  after_script:
    - rm -r -f ~/.ssh
    - chmod -x ./ci/db_dump.sh
    - docker image prune -f -a && docker container prune -f || true
  tags:
    - back
#  when: manual

