stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - docker login --username $DOCKER_USER --password "$DOCKER_KEY"
#    - echo "$DOCKER_KEY" | docker login --username $DOCKER_USER --password-stdin
  script:
    - echo "BUILD STAGE"
    - echo $USER
    - docker build --network host -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master

deploy:
  stage: deploy
  image: docker:20.10-git
  dependencies:
    - build
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - '[[ -f /.dockerenv || -d /run/secrets/kubernetes.io/serviceaccount ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$DOCKER_KEY" | docker login --username $DOCKER_USER --password-stdin
  script:
    - echo "DEPLOY STAGE"
# echo "dckr_pat_KSYQ2ik-mVXD5FuOYBJ1QWJAAkA" | docker login --username marelboro

#    - docker compose --env-file $env pull
#    - docker compose --env-file $env run django manage.py makemigrations
#    - docker compose --env-file $env run django manage.py migrate
#    - docker compose --env-file $env down --timeout=60 --remove-orphans
#    - docker compose --env-file $env up --build --detach
#    - docker image prune -f || true
  only:
    - master
