stages:
  - build
  - deploy

build:
  stage: build
  services:
    - docker:stable-dind
  before_script:
    - echo "$DOCKER_KEY" | docker login --username $DOCKER_USER --password-stdin
  script:
    - docker build --network host -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

deploy:
  stage: deploy
  only:
    - master
  script:
    - apk --no-cache update
    - apk --no-cache add openssh-client
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh $SERVER_USER@$SERVER_IP "bash -s" < deploy_script.sh




