stages:
  - build
  - delivery
#  - deploy

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up


delivery:
  stage: delivery
  script:
    - echo $DOCKER_KEY | docker login -u $DOCKER_USER --password-stdin
    - docker tag pw_main_app:latest $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE


