version: '3.7'

services:
  django:
    container_name: "django"
    image: ${CI_REGISTRY_IMAGE}
    env_file:
      - $env
    tty: true
#    read_only: true
    volumes:
      - .:/app/main/
    ports:
      - "8000:8000"

  celery-worker:
    container_name: "celery-worker"
    image: ${CI_REGISTRY_IMAGE}
    entrypoint:
      - "python"
    command: [ "-m", "celery", "-A", "pulsewave", "worker", "-l", "INFO" ]
    env_file:
      - $env
    tty: true
    volumes:
      - .:/app/main/

  celery-beat:
    container_name: "celery-beat"
    image: ${CI_REGISTRY_IMAGE}
    entrypoint:
      - "python"
    command: ["-m", "celery", "-A", "pulsewave", "beat", "-l", "INFO"]
    tty: true
    env_file:
      - $env
    read_only: true
    volumes:
      - .:/app/main/

  bot:
    container_name: "bot"
    image: ${CI_REGISTRY_IMAGE}
#    entrypoint:
#      - "python"
    command: ["python", "manage.py", "startbot"]
    read_only: true
    env_file:
      - $env
    volumes:
      - .:/app/main/


networks:
  default:
    name: ${NETWORK}
    external: true



