version: '3.7'

services:
  django:
    container_name: "django"
    image: ${CI_REGISTRY_IMAGE}
    env_file:
      - $env
    tty: true
    read_only: true
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    healthcheck:
      test: "curl --fail http://localhost:8000/api/schema/swagger-ui/"
      interval: 30s
      timeout: 2s
      retries: 3
      start_period: 1m

  celery-worker:
    container_name: "celery-worker"
    image: ${CI_REGISTRY_IMAGE}
    command: [ "-m", "celery", "-A", "pulsewave", "worker", "-l", "INFO" ]
    env_file:
      - $env
    tty: true
    volumes:
      - .:/app
    healthcheck:
      test: [ "CMD-SHELL", "[[ $(($(date +%s)-$(stat -c %Y /tmp/celery_heartbeat))) -gt 2 ]] && exit 1 || exit 0" ]
      interval: 30s
      timeout: 2s
      retries: 2
      start_period: 30s

  celery-beat:
    container_name: "celery-beat"
    image: ${CI_REGISTRY_IMAGE}
    command: ["-m", "celery", "-A", "pulsewave", "beat", "-l", "INFO"]
    tty: true
    env_file:
      - $env
    volumes:
      - .:/app
    healthcheck:
      test: [ "CMD-SHELL", "[[ $(($(date +%s)-$(stat -c %Y /tmp/celery_heartbeat))) -gt 10 ]] && exit 1 || exit 0" ]
      interval: 10s
      timeout: 2s
      retries: 1
      start_period: 1m

  bot:
    container_name: "bot"
    image: ${CI_REGISTRY_IMAGE}
    command: ["manage.py", "startbot"]
    read_only: true
    env_file:
      - $env
    volumes:
      - .:/app

networks:
  default:
    name: ${NETWORK}
    external: true



