version: '3.7'

services:
  django:
    container_name: "django"
    image: ${CI_REGISTRY_IMAGE}
    env_file:
      - $env
    tty: true
    volumes:
      - .:/app/main/
    ports:
      - "8000:8000"
      - "465:465"

  celery-worker:
    container_name: "celery-worker"
    image: ${CI_REGISTRY_IMAGE}
    entrypoint:
      - "python3"
    command: [ "-m", "celery", "-A", "pulsewave", "worker", "-l", "INFO" ]
    env_file:
      - $env
    tty: true
    volumes:
      - .:/app/main/

  celery-beat:
    container_name: "celery-beat"
    image: ${CI_REGISTRY_IMAGE}
    entrypoint:
      - "python3"
    command: ["-m", "celery", "-A", "pulsewave", "beat", "-l", "INFO"]
    env_file:
      - $env
    read_only: true
    volumes:
      - .:/app/main/

networks:
  default:
    name: "server-bridge"
    external: true



#  bot:
#    container_name: "bot"
#    image: marelboro/pw-main-app:latest
#    command: python3 manage.py startbot
#    tty: true
#    env_file:
#      - $env
#    volumes:
#      - .:/usr/home/web/:ro
#    environment:
#      SECRET_KEY: "${SECRET_KEY}"
#      DB_NAME: "${DB_NAME}"
#      DB_HOST: "${DB_HOST}"
#      DB_PASSWORD: "${DB_PASSWORD}"
#      DB_USER: "${DB_USER}"
#      DB_PORT: "${DB_PORT}"
#      REDIS_HOST: "${REDIS_HOST}"
#    depends_on:
#      - redis
