.app-release: &app-release
  chartPath: .ci/charts/web-app
  wait: true
  upgradeOnChange: true

.postgres-release: &postgres-release
  repo: https://charts.bitnami.com/bitnami
  remoteChart: postgresql
  version: "12.1.10"
  wait: true
  upgradeOnChange: true

.redis-release: &redis-reference
  repo: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  remoteChart: redis
  version: "10.8.2"
  wait: true
  upgradeOnChange: true

.helm-flags: &helm-flags
  install:
    - "--timeout=7m"
  upgrade:
    - "--timeout=7m"

apiVersion: skaffold/v3
kind: Config
metadata:
  name: pwave-backend-drfapi
build:
  artifacts:
    - image: pwave-backend-drfapi
      context: .
      docker:
        dockerfile: ./Dockerfile
deploy:
  kubeContext: pnpl-tech
profiles:
  - name: prod
    activation:
      - env: CI_COMMIT_BRANCH=master|main
    build:
      tagPolicy:
        envTemplate:
          template: "prod-{{.CI_COMMIT_SHORT_SHA}}"
    deploy:
      helm:
        flags: *helm-flags
        releases:
          # - <<: *postgres-release
          #   name: &postgres-release-name "random-dessert-postgresql"
          #   namespace: default
          #   setValueTemplates:
          #     global.postgresql.auth.password: "{{.CI_POSTGRES_USER_PASSWORD}}"
          #   valuesFiles:
          #     - ".ci/env.values/postgresql.yaml"
          #     - ".ci/env.values/prod/postgresql.yaml"
          - <<: *redis-reference
            name: &redis-release-name pwave-backend-redis
            namespace: default
            valuesFiles:
              - ".ci/env.values/redis.yaml"
              - ".ci/env.values/prod/redis.yaml"
          - <<: *app-release
            name: &app-release-name "pwave-backend-drfapi"
            namespace: default
            setValueTemplates:
              image.name: "{{.IMAGE_FULLY_QUALIFIED_pwave_backend_drfapi}}"
              hooks.jobs.migrations.image: "{{.IMAGE_FULLY_QUALIFIED_pwave_backend_drfapi}}"
              GIT_REPO: "{{.CI_PROJECT_NAME}}"
              CI_FQDN: "{{.CI_FQDN}}"
              CI_TLS_SECRET_NAME: "{{.CI_TLS_SECRET_NAME}}-tls"
              APP_DJANGO_SECRET_KEY: "{{.APP_DJANGO_SECRET_KEY}}"
              APP_EMAIL_HOST_USER: "{{.APP_EMAIL_HOST_USER}}"
              APP_EMAIL_HOST_PASSWORD: "{{.APP_EMAIL_HOST_PASSWORD}}"
              APP_REDIS_BROKER: *redis-release-name
              BOT_TOKEN: "{{.APP_BOT_TOKEN}}"
            valuesFiles:
              - ".ci/env.values/app.yaml"
              - ".ci/env.values/hooks.yaml"
              - ".ci/env.values/cronjobs.yaml"
              - ".ci/env.values/prod/app.yaml"
              - ".ci/env.values/prod/hooks.yaml"
              - ".ci/env.values/prod/cronjobs.yaml"
          - <<: *app-release
            name: &app-celery-beat "pwave-celery-beat"
            namespace: default
            setValueTemplates:
              image.name: "{{.IMAGE_FULLY_QUALIFIED_pwave_backend_drfapi}}"
              GIT_REPO: *app-celery-beat
              APP_DJANGO_SECRET_KEY: "{{.APP_DJANGO_SECRET_KEY}}"
              APP_EMAIL_HOST_USER: "{{.APP_EMAIL_HOST_USER}}"
              APP_EMAIL_HOST_PASSWORD: "{{.APP_EMAIL_HOST_PASSWORD}}"
              APP_REDIS_BROKER: *redis-release-name
            valuesFiles:
              - ".ci/env.values/celery-beat.yaml"
              - ".ci/env.values/prod/celery.yaml"
          - <<: *app-release
            name: &app-celery-worker "pwave-celery-worker"
            namespace: default
            setValueTemplates:
              image.name: "{{.IMAGE_FULLY_QUALIFIED_pwave_backend_drfapi}}"
              GIT_REPO: *app-celery-worker
              APP_DJANGO_SECRET_KEY: "{{.APP_DJANGO_SECRET_KEY}}"
              APP_EMAIL_HOST_USER: "{{.APP_EMAIL_HOST_USER}}"
              APP_EMAIL_HOST_PASSWORD: "{{.APP_EMAIL_HOST_PASSWORD}}"
              APP_REDIS_BROKER: *redis-release-name
            valuesFiles:
              - ".ci/env.values/celery-worker.yaml"
              - ".ci/env.values/prod/celery.yaml"
          - <<: *app-release
            name: &app-bot pwave-backend-bot
            namespace: default
            setValueTemplates:
              image.name: "{{.IMAGE_FULLY_QUALIFIED_pwave_backend_drfapi}}"
              GIT_REPO: *app-bot
              APP_DJANGO_SECRET_KEY: "{{.APP_DJANGO_SECRET_KEY}}"
              BOT_TOKEN: "{{.APP_BOT_TOKEN}}"
            valuesFiles:
              - ".ci/env.values/bot.yaml"
              - ".ci/env.values/prod/bot.yaml"
