# Generated by Django 4.2.5 on 2023-10-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscriber',
            field=models.BooleanField(default=False, verbose_name='Подписан на рассылки'),
        ),
    ]
