env:
  DB_NAME:
    valueFrom:
      secretKeyRef:
        name: pulsewave-pgsql-creds
        key: database
  DB_USER:
    valueFrom:
      secretKeyRef:
        name: pulsewave-pgsql-creds
        key: user
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: pulsewave-pgsql-creds
        key: password
  DB_HOST:
    valueFrom:
      secretKeyRef:
        name: pulsewave-pgsql-creds
        key: host
  DB_PORT: 6432
  SECRET_KEY: "{{ .Values.APP_DJANGO_SECRET_KEY }}"
  EMAIL_HOST_USER: "{{ .Values.APP_EMAIL_HOST_USER }}"
  EMAIL_HOST_PASSWORD: "{{ .Values.APP_EMAIL_HOST_PASSWORD }}"
  PYTHONUNBUFFERED: 1
  REDIS_HOST: "{{ .Values.APP_REDIS_BROKER }}-master"
  AWS_KEY_IDENTIFICATOR:
    valueFrom:
      secretKeyRef:
        name: pwave-backend-s3-creds
        key: AWS_KEY_IDENTIFICATOR
  AWS_SECRET_KEY:
    valueFrom:
      secretKeyRef:
        name: pwave-backend-s3-creds
        key: AWS_SECRET_KEY
  BOT_TOKEN: "{{ .Values.BOT_TOKEN }}"

imagePullSecrets:
  - name: gitlab-cr

replicaCount: 1

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
  hosts:
    - host: "{{ .Values.CI_FQDN }}"
      paths:
        - "/"
