# Generated by Django 4.2.9 on 2024-02-03 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telebotid',
            old_name='telegram_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='telebotid',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
