# Generated by Django 4.2.10 on 2024-02-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_rename_telegram_name_telebotid_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telebotid',
            name='telegram_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
